# Generated by Django 2.0.4 on 2018-05-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetsToCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatureId', models.IntegerField()),
                ('creatureName', models.TextField()),
                ('source', models.CharField(max_length=300)),
                ('zone', models.TextField()),
                ('investmentType', models.CharField(max_length=1)),
                ('investmentValue', models.IntegerField()),
            ],
        ),
    ]
